// Code generated from the archived route contract; DO NOT EDIT.
// Compact form keeps migration gates without embedding repeated prose per route.
package main

type routeContract struct {
	ID                 string
	Endpoint           string
	Methods            []string
	Domain             string
	LegacySymbol       string
	GoPattern          string
	CoveredByGo        bool
	HandlerMode        string
	RiskLevel          string
	RequiresAuth       bool
	RequiresCSRF       bool
	RequiresPermission bool
	RequestContract    []string
	ResponseContract   []string
	FailureContract    []string
	MigrationNotes     []string
}

type routeContractSeed struct {
	ID                 string
	Endpoint           string
	Methods            []string
	Domain             string
	LegacySymbol       string
	GoPattern          string
	CoveredByGo        bool
	HandlerMode        string
	RiskLevel          string
	RequiresAuth       bool
	RequiresCSRF       bool
	RequiresPermission bool
}

var defaultRouteRequestContract = []string{
	`accept the archived request shape`,
	`normalize camelCase and snake_case fields before business logic`,
	`reject malformed JSON with a structured JSON error`,
	`do not read files or execute commands before authorization`,
}

var defaultRouteResponseContract = []string{
	`return application/json for JSON APIs and text/event-stream for SSE routes`,
	`do not return HTML traceback pages for API failures`,
	`never include plaintext API keys, tokens, or local secrets`,
	`include success/available/error fields when a capability is unavailable`,
}

var defaultRouteFailureContract = []string{
	`return structured unavailable when an optional worker or model dependency is missing`,
	`return permission_required before any high-risk side effect`,
	`write an audit record for allowed and denied high-risk actions`,
	`keep fallback modes honest about unavailable capabilities`,
}

func buildRouteContracts(seeds []routeContractSeed) []routeContract {
	out := make([]routeContract, 0, len(seeds))
	for _, seed := range seeds {
		out = append(out, routeContract{
			ID: seed.ID, Endpoint: seed.Endpoint, Methods: seed.Methods, Domain: seed.Domain, LegacySymbol: seed.LegacySymbol, GoPattern: seed.GoPattern,
			CoveredByGo: seed.CoveredByGo, HandlerMode: seed.HandlerMode, RiskLevel: seed.RiskLevel, RequiresAuth: seed.RequiresAuth, RequiresCSRF: seed.RequiresCSRF, RequiresPermission: seed.RequiresPermission,
			RequestContract: defaultRouteRequestContract, ResponseContract: defaultRouteResponseContract, FailureContract: defaultRouteFailureContract,
			MigrationNotes: []string{`archived route contract retained as a migration gate`, `coverage is mandatory but behavior tests remain the deletion gate`, `workspace routes must cover traversal and symlink escape`, `provider routes must use fake upstream tests and assert no key leakage`},
		})
	}
	return out
}

var legacyRouteContractSeeds = []routeContractSeed{
	{ID: `LEGACY-ROUTE-001`, Endpoint: `/`, Methods: []string{`GET`}, Domain: `home`, LegacySymbol: `index`, GoPattern: `/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-002`, Endpoint: `/ab/experiments`, Methods: []string{`POST`}, Domain: `ab`, LegacySymbol: `ab_create`, GoPattern: `/ab/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-003`, Endpoint: `/ab/experiments/<exp_id>`, Methods: []string{`DELETE`}, Domain: `ab`, LegacySymbol: `ab_delete`, GoPattern: `/ab/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-004`, Endpoint: `/ab/experiments/<exp_id>/metrics`, Methods: []string{`POST`}, Domain: `ab`, LegacySymbol: `ab_metrics`, GoPattern: `/ab/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-005`, Endpoint: `/ab/experiments/<exp_id>/status`, Methods: []string{`POST`}, Domain: `ab`, LegacySymbol: `ab_status`, GoPattern: `/ab/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-006`, Endpoint: `/ab/overview`, Methods: []string{`GET`}, Domain: `ab`, LegacySymbol: `ab_overview`, GoPattern: `/ab/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-007`, Endpoint: `/account/profile`, Methods: []string{`GET`, `POST`}, Domain: `account`, LegacySymbol: `account_profile_api`, GoPattern: `/account/profile`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-008`, Endpoint: `/account/sessions`, Methods: []string{`DELETE`, `GET`}, Domain: `account`, LegacySymbol: `account_sessions_api`, GoPattern: `/account/sessions`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-009`, Endpoint: `/account/tokens`, Methods: []string{`DELETE`, `GET`, `POST`}, Domain: `account`, LegacySymbol: `account_tokens_api`, GoPattern: `/account/tokens`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-010`, Endpoint: `/agent-ide`, Methods: []string{`GET`}, Domain: `agent_ide`, LegacySymbol: `agent_ide_page`, GoPattern: `/agent-ide`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-011`, Endpoint: `/agent/abort`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_abort_endpoint`, GoPattern: `/agent/abort`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-012`, Endpoint: `/agent/accounts`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `agent_accounts`, GoPattern: `/agent/accounts`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-013`, Endpoint: `/agent/api-status`, Methods: []string{`GET`, `POST`}, Domain: `agent`, LegacySymbol: `agent_api_status`, GoPattern: `/agent/api-status`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-014`, Endpoint: `/agent/api-test`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_api_test`, GoPattern: `/agent/api-test`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-015`, Endpoint: `/agent/audit/logs`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `audit_logs`, GoPattern: `/agent/audit/logs`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-016`, Endpoint: `/agent/audit/stats`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `audit_stats`, GoPattern: `/agent/audit/stats`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-017`, Endpoint: `/agent/browsable-dirs`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_browsable_dirs`, GoPattern: `/agent/browsable-dirs`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-018`, Endpoint: `/agent/browser/fetch`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_browser_fetch`, GoPattern: `/agent/browser/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-019`, Endpoint: `/agent/browser/open`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_browser_open`, GoPattern: `/agent/browser/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-020`, Endpoint: `/agent/browser/search`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_browser_search`, GoPattern: `/agent/browser/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-021`, Endpoint: `/agent/compile`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_compile`, GoPattern: `/agent/compile`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-022`, Endpoint: `/agent/events`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `agent_events`, GoPattern: `/agent/events`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-023`, Endpoint: `/agent/file-analyzer/analyze`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `file_analyzer_analyze`, GoPattern: `/agent/file-analyzer/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-024`, Endpoint: `/agent/file-analyzer/dependencies`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `file_analyzer_deps`, GoPattern: `/agent/file-analyzer/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-025`, Endpoint: `/agent/file-analyzer/files`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `file_analyzer_files`, GoPattern: `/agent/file-analyzer/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-026`, Endpoint: `/agent/file-analyzer/recommendations`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `file_analyzer_recs`, GoPattern: `/agent/file-analyzer/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-027`, Endpoint: `/agent/file-analyzer/references`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `file_analyzer_refs`, GoPattern: `/agent/file-analyzer/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-028`, Endpoint: `/agent/file-analyzer/stats`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `file_analyzer_stats`, GoPattern: `/agent/file-analyzer/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-029`, Endpoint: `/agent/file-analyzer/tree`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `file_analyzer_tree`, GoPattern: `/agent/file-analyzer/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-030`, Endpoint: `/agent/file-tree`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_file_tree`, GoPattern: `/agent/file-tree`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-031`, Endpoint: `/agent/file-write`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_file_write`, GoPattern: `/agent/file-write`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-032`, Endpoint: `/agent/identify`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_identify`, GoPattern: `/agent/identify`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-033`, Endpoint: `/agent/import-env`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_import_env`, GoPattern: `/agent/import-env`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-034`, Endpoint: `/agent/import-files`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_import_files`, GoPattern: `/agent/import-files`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-035`, Endpoint: `/agent/open-project`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_open_project`, GoPattern: `/agent/open-project`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-036`, Endpoint: `/agent/permission/config`, Methods: []string{`GET`, `POST`}, Domain: `agent`, LegacySymbol: `permission_config`, GoPattern: `/agent/permission/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-037`, Endpoint: `/agent/permission/respond`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `permission_respond`, GoPattern: `/agent/permission/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-038`, Endpoint: `/agent/permission/rule`, Methods: []string{`DELETE`, `POST`}, Domain: `agent`, LegacySymbol: `permission_rule`, GoPattern: `/agent/permission/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-039`, Endpoint: `/agent/permission/sandbox-dir`, Methods: []string{`DELETE`, `POST`}, Domain: `agent`, LegacySymbol: `permission_sandbox_dir`, GoPattern: `/agent/permission/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-040`, Endpoint: `/agent/plugins`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `agent_plugins_list`, GoPattern: `/agent/plugins`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-041`, Endpoint: `/agent/plugins/<plugin_id>/toggle`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_plugins_toggle`, GoPattern: `/agent/plugins/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-042`, Endpoint: `/agent/project-output`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_project_output`, GoPattern: `/agent/project-output`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-043`, Endpoint: `/agent/project-status`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_project_status`, GoPattern: `/agent/project-status`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-044`, Endpoint: `/agent/read-file`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_read_file`, GoPattern: `/agent/read-file`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-045`, Endpoint: `/agent/revert-file`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_revert_file`, GoPattern: `/agent/revert-file`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-046`, Endpoint: `/agent/run`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_run_endpoint`, GoPattern: `/agent/run`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-047`, Endpoint: `/agent/run-project`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_run_project`, GoPattern: `/agent/run-project`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-048`, Endpoint: `/agent/stop-project`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_stop_project`, GoPattern: `/agent/stop-project`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-049`, Endpoint: `/agent/system/info`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `agent_system_info`, GoPattern: `/agent/system/info`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-050`, Endpoint: `/agent/tasks`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_tasks_create`, GoPattern: `/agent/tasks`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-051`, Endpoint: `/agent/tasks/<task_id>`, Methods: []string{`DELETE`, `GET`, `PATCH`}, Domain: `agent`, LegacySymbol: `agent_tasks_manage`, GoPattern: `/agent/tasks/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-052`, Endpoint: `/agent/tasks/<task_id>/activate`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_tasks_activate`, GoPattern: `/agent/tasks/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-053`, Endpoint: `/agent/tasks/tree`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `agent_tasks_tree`, GoPattern: `/agent/tasks/tree`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-054`, Endpoint: `/agent/terminal/exec`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_terminal_exec`, GoPattern: `/agent/terminal/exec`, CoveredByGo: true, HandlerMode: `permission_guarded`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-055`, Endpoint: `/agent/terminal/kill`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_terminal_kill`, GoPattern: `/agent/terminal/kill`, CoveredByGo: true, HandlerMode: `permission_guarded`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-056`, Endpoint: `/agent/tools`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `agent_tools_endpoint`, GoPattern: `/agent/tools`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-057`, Endpoint: `/agent/upload-device-files`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_upload_device_files`, GoPattern: `/agent/upload-device-files`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-058`, Endpoint: `/agent/user-info`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `agent_user_info`, GoPattern: `/agent/user-info`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-059`, Endpoint: `/agent/v2/command-safety`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `v2_command_safety`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-060`, Endpoint: `/agent/v2/executor/status`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `v2_executor_status`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-061`, Endpoint: `/agent/v2/permissions/audit`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `v2_permission_audit`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-062`, Endpoint: `/agent/v2/permissions/denials`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `v2_permission_denials`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-063`, Endpoint: `/agent/v2/permissions/mode`, Methods: []string{`GET`, `POST`}, Domain: `agent`, LegacySymbol: `v2_permission_mode`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-064`, Endpoint: `/agent/v2/permissions/pending`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `v2_permission_pending`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-065`, Endpoint: `/agent/v2/permissions/respond`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `v2_permission_respond`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-066`, Endpoint: `/agent/v2/permissions/rules`, Methods: []string{`DELETE`, `GET`, `POST`}, Domain: `agent`, LegacySymbol: `v2_permission_rules`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-067`, Endpoint: `/agent/v2/permissions/stats`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `v2_permission_stats`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-068`, Endpoint: `/agent/v2/sessions`, Methods: []string{`GET`}, Domain: `agent`, LegacySymbol: `v2_sessions_list`, GoPattern: `/agent/v2/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-069`, Endpoint: `/agent/write-file`, Methods: []string{`POST`}, Domain: `agent`, LegacySymbol: `agent_write_file`, GoPattern: `/agent/write-file`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-070`, Endpoint: `/alerts/overview`, Methods: []string{`GET`}, Domain: `alerts`, LegacySymbol: `alerts_overview`, GoPattern: `/alerts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-071`, Endpoint: `/alerts/rules`, Methods: []string{`POST`}, Domain: `alerts`, LegacySymbol: `alerts_rule_create`, GoPattern: `/alerts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-072`, Endpoint: `/alerts/rules/<rule_id>`, Methods: []string{`DELETE`}, Domain: `alerts`, LegacySymbol: `alerts_rule_delete`, GoPattern: `/alerts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-073`, Endpoint: `/alerts/rules/<rule_id>/status`, Methods: []string{`POST`}, Domain: `alerts`, LegacySymbol: `alerts_rule_status`, GoPattern: `/alerts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-074`, Endpoint: `/api/account/auto-fill`, Methods: []string{`GET`}, Domain: `api`, LegacySymbol: `api_account_auto_fill`, GoPattern: `/api/account/auto-fill`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-075`, Endpoint: `/api/account/saved-config`, Methods: []string{`GET`}, Domain: `api`, LegacySymbol: `api_account_saved_config`, GoPattern: `/api/account/saved-config`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-076`, Endpoint: `/api/chat`, Methods: []string{`POST`}, Domain: `api`, LegacySymbol: `api_chat_compat`, GoPattern: `/api/chat`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-077`, Endpoint: `/api/config`, Methods: []string{`GET`, `POST`}, Domain: `api`, LegacySymbol: `api_config_compat`, GoPattern: `/api/config`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-078`, Endpoint: `/api/device/bind`, Methods: []string{`POST`}, Domain: `api`, LegacySymbol: `api_device_bind`, GoPattern: `/api/device/bind`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-079`, Endpoint: `/api/device/info`, Methods: []string{`GET`}, Domain: `api`, LegacySymbol: `api_device_info`, GoPattern: `/api/device/info`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-080`, Endpoint: `/api/device/unbind`, Methods: []string{`POST`}, Domain: `api`, LegacySymbol: `api_device_unbind`, GoPattern: `/api/device/unbind`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-081`, Endpoint: `/api/model-status`, Methods: []string{`GET`, `POST`}, Domain: `api`, LegacySymbol: `api_model_status_compat`, GoPattern: `/api/model-status`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-082`, Endpoint: `/api/prompts`, Methods: []string{`GET`}, Domain: `api`, LegacySymbol: `api_prompts`, GoPattern: `/api/prompts`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-083`, Endpoint: `/api/prompts/custom`, Methods: []string{`POST`}, Domain: `api`, LegacySymbol: `api_prompts_custom_create`, GoPattern: `/api/prompts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-084`, Endpoint: `/api/prompts/custom/<tpl_id>`, Methods: []string{`DELETE`}, Domain: `api`, LegacySymbol: `api_prompts_custom_delete`, GoPattern: `/api/prompts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-085`, Endpoint: `/api/prompts/favorites`, Methods: []string{`DELETE`, `GET`, `POST`}, Domain: `api`, LegacySymbol: `api_prompts_favorites`, GoPattern: `/api/prompts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-086`, Endpoint: `/api/prompts/usage`, Methods: []string{`POST`}, Domain: `api`, LegacySymbol: `api_prompts_usage`, GoPattern: `/api/prompts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-087`, Endpoint: `/api/roles`, Methods: []string{`GET`}, Domain: `api`, LegacySymbol: `api_roles`, GoPattern: `/api/roles`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-088`, Endpoint: `/api/version`, Methods: []string{`GET`}, Domain: `api`, LegacySymbol: `api_version`, GoPattern: `/api/version`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-089`, Endpoint: `/artifacts`, Methods: []string{`POST`}, Domain: `artifacts`, LegacySymbol: `artifacts_create`, GoPattern: `/artifacts`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-090`, Endpoint: `/artifacts/<artifact_id>`, Methods: []string{`DELETE`}, Domain: `artifacts`, LegacySymbol: `artifacts_delete`, GoPattern: `/artifacts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-091`, Endpoint: `/artifacts/<artifact_id>/pin`, Methods: []string{`POST`}, Domain: `artifacts`, LegacySymbol: `artifacts_pin`, GoPattern: `/artifacts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-092`, Endpoint: `/artifacts/<artifact_id>/restore`, Methods: []string{`POST`}, Domain: `artifacts`, LegacySymbol: `artifacts_restore`, GoPattern: `/artifacts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-093`, Endpoint: `/artifacts/<artifact_id>/versions`, Methods: []string{`GET`}, Domain: `artifacts`, LegacySymbol: `artifacts_versions`, GoPattern: `/artifacts/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-094`, Endpoint: `/audio/<filename>`, Methods: []string{`GET`}, Domain: `audio`, LegacySymbol: `serve_audio`, GoPattern: `/audio/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-095`, Endpoint: `/auth/account`, Methods: []string{`GET`, `PUT`}, Domain: `auth`, LegacySymbol: `auth_account`, GoPattern: `/auth/account`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-096`, Endpoint: `/auth/admin/accounts`, Methods: []string{`GET`}, Domain: `auth`, LegacySymbol: `auth_admin_accounts`, GoPattern: `/auth/admin/accounts`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: false, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-097`, Endpoint: `/auth/admin/role`, Methods: []string{`POST`}, Domain: `auth`, LegacySymbol: `auth_admin_role`, GoPattern: `/auth/admin/role`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-098`, Endpoint: `/auth/login`, Methods: []string{`GET`, `POST`}, Domain: `auth`, LegacySymbol: `auth_login`, GoPattern: `/auth/login`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-099`, Endpoint: `/auth/logout`, Methods: []string{`POST`}, Domain: `auth`, LegacySymbol: `auth_logout`, GoPattern: `/auth/logout`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-100`, Endpoint: `/auth/logout-all`, Methods: []string{`POST`}, Domain: `auth`, LegacySymbol: `auth_logout_all`, GoPattern: `/auth/logout-all`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-101`, Endpoint: `/auth/password-reset/confirm`, Methods: []string{`POST`}, Domain: `auth`, LegacySymbol: `auth_password_reset_confirm`, GoPattern: `/auth/password-reset/confirm`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-102`, Endpoint: `/auth/password-reset/request`, Methods: []string{`POST`}, Domain: `auth`, LegacySymbol: `auth_password_reset_request`, GoPattern: `/auth/password-reset/request`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-103`, Endpoint: `/auth/register`, Methods: []string{`POST`}, Domain: `auth`, LegacySymbol: `auth_register`, GoPattern: `/auth/register`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-104`, Endpoint: `/auth/setup`, Methods: []string{`GET`, `POST`}, Domain: `auth`, LegacySymbol: `auth_setup`, GoPattern: `/auth/setup`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-105`, Endpoint: `/auth/token`, Methods: []string{`POST`}, Domain: `auth`, LegacySymbol: `auth_token`, GoPattern: `/auth/token`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-106`, Endpoint: `/background`, Methods: []string{`GET`}, Domain: `background`, LegacySymbol: `background`, GoPattern: `/background`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-107`, Endpoint: `/chat`, Methods: []string{`POST`}, Domain: `chat`, LegacySymbol: `chat_endpoint`, GoPattern: `/chat`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-108`, Endpoint: `/chat/completions`, Methods: []string{`POST`}, Domain: `chat`, LegacySymbol: `chat_completions_compat`, GoPattern: `/chat/completions`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-109`, Endpoint: `/chats/export`, Methods: []string{`GET`}, Domain: `chats`, LegacySymbol: `chats_export_api`, GoPattern: `/chats/export`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-110`, Endpoint: `/code/execute`, Methods: []string{`POST`}, Domain: `code`, LegacySymbol: `code_execute`, GoPattern: `/code/execute`, CoveredByGo: true, HandlerMode: `permission_guarded`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-111`, Endpoint: `/console/governance-report`, Methods: []string{`GET`}, Domain: `console`, LegacySymbol: `generate_governance_report`, GoPattern: `/console/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-112`, Endpoint: `/console/overview`, Methods: []string{`GET`}, Domain: `console`, LegacySymbol: `console_overview`, GoPattern: `/console/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-113`, Endpoint: `/console/recommendations`, Methods: []string{`GET`}, Domain: `console`, LegacySymbol: `console_recommendations`, GoPattern: `/console/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-114`, Endpoint: `/dataflow/stats`, Methods: []string{`GET`}, Domain: `dataflow`, LegacySymbol: `dataflow_stats`, GoPattern: `/dataflow/stats`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-115`, Endpoint: `/deepseek-icon`, Methods: []string{`GET`}, Domain: `deepseek_icon`, LegacySymbol: `deepseek_icon`, GoPattern: `/deepseek-icon`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-116`, Endpoint: `/deepseek/chat`, Methods: []string{`POST`}, Domain: `deepseek`, LegacySymbol: `deepseek_chat`, GoPattern: `/deepseek/chat`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-117`, Endpoint: `/deepseek/test`, Methods: []string{`POST`}, Domain: `deepseek`, LegacySymbol: `deepseek_test`, GoPattern: `/deepseek/test`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-118`, Endpoint: `/dependencies/analyze`, Methods: []string{`GET`}, Domain: `dependencies`, LegacySymbol: `analyze_dependencies`, GoPattern: `/dependencies/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-119`, Endpoint: `/dependencies/security-check`, Methods: []string{`GET`}, Domain: `dependencies`, LegacySymbol: `security_check`, GoPattern: `/dependencies/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-120`, Endpoint: `/deploy/execute`, Methods: []string{`POST`}, Domain: `deploy`, LegacySymbol: `execute_deploy`, GoPattern: `/deploy/execute`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-121`, Endpoint: `/external/config`, Methods: []string{`POST`}, Domain: `external`, LegacySymbol: `external_config_save`, GoPattern: `/external/config`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-122`, Endpoint: `/external/test`, Methods: []string{`POST`}, Domain: `external`, LegacySymbol: `external_test`, GoPattern: `/external/test`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-123`, Endpoint: `/favicon.ico`, Methods: []string{`GET`}, Domain: `favicon.ico`, LegacySymbol: `favicon`, GoPattern: `/favicon.ico`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-124`, Endpoint: `/finetune/dataset/<dataset_id>`, Methods: []string{`DELETE`}, Domain: `finetune`, LegacySymbol: `finetune_delete_dataset`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-125`, Endpoint: `/finetune/dataset/upload`, Methods: []string{`POST`}, Domain: `finetune`, LegacySymbol: `finetune_upload_dataset`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-126`, Endpoint: `/finetune/datasets`, Methods: []string{`GET`}, Domain: `finetune`, LegacySymbol: `finetune_get_datasets`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-127`, Endpoint: `/finetune/job`, Methods: []string{`POST`}, Domain: `finetune`, LegacySymbol: `finetune_create_job`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-128`, Endpoint: `/finetune/job/<job_id>`, Methods: []string{`DELETE`}, Domain: `finetune`, LegacySymbol: `finetune_delete_job`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-129`, Endpoint: `/finetune/job/<job_id>/logs`, Methods: []string{`GET`}, Domain: `finetune`, LegacySymbol: `finetune_get_job_logs`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-130`, Endpoint: `/finetune/job/<job_id>/start`, Methods: []string{`POST`}, Domain: `finetune`, LegacySymbol: `finetune_start_job`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-131`, Endpoint: `/finetune/job/<job_id>/stop`, Methods: []string{`POST`}, Domain: `finetune`, LegacySymbol: `finetune_stop_job`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-132`, Endpoint: `/finetune/jobs`, Methods: []string{`GET`}, Domain: `finetune`, LegacySymbol: `finetune_get_jobs`, GoPattern: `/finetune/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-133`, Endpoint: `/git/status`, Methods: []string{`GET`}, Domain: `git`, LegacySymbol: `git_status`, GoPattern: `/git/status`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-134`, Endpoint: `/header-img`, Methods: []string{`GET`}, Domain: `header_img`, LegacySymbol: `header_img`, GoPattern: `/header-img`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-135`, Endpoint: `/hero-img`, Methods: []string{`GET`}, Domain: `hero_img`, LegacySymbol: `hero_img`, GoPattern: `/hero-img`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-136`, Endpoint: `/integrations`, Methods: []string{`POST`}, Domain: `integrations`, LegacySymbol: `integrations_create`, GoPattern: `/integrations`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-137`, Endpoint: `/integrations/<integration_id>`, Methods: []string{`DELETE`}, Domain: `integrations`, LegacySymbol: `integrations_delete`, GoPattern: `/integrations/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-138`, Endpoint: `/integrations/<integration_id>/status`, Methods: []string{`POST`}, Domain: `integrations`, LegacySymbol: `integrations_status`, GoPattern: `/integrations/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-139`, Endpoint: `/integrations/overview`, Methods: []string{`GET`}, Domain: `integrations`, LegacySymbol: `integrations_overview`, GoPattern: `/integrations/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-140`, Endpoint: `/kb/add`, Methods: []string{`POST`}, Domain: `kb`, LegacySymbol: `kb_add`, GoPattern: `/kb/add`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-141`, Endpoint: `/kb/search`, Methods: []string{`POST`}, Domain: `kb`, LegacySymbol: `kb_search`, GoPattern: `/kb/search`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-142`, Endpoint: `/lora/list`, Methods: []string{`GET`}, Domain: `lora`, LegacySymbol: `lora_list`, GoPattern: `/lora/list`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-143`, Endpoint: `/lora/load`, Methods: []string{`POST`}, Domain: `lora`, LegacySymbol: `lora_load`, GoPattern: `/lora/load`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-144`, Endpoint: `/mcp/execute`, Methods: []string{`POST`}, Domain: `mcp`, LegacySymbol: `mcp_execute_tool`, GoPattern: `/mcp/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-145`, Endpoint: `/mcp/plugin/<plugin_id>`, Methods: []string{`GET`}, Domain: `mcp`, LegacySymbol: `mcp_get_plugin`, GoPattern: `/mcp/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-146`, Endpoint: `/mcp/plugin/<plugin_id>/config`, Methods: []string{`POST`}, Domain: `mcp`, LegacySymbol: `mcp_update_plugin_config`, GoPattern: `/mcp/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-147`, Endpoint: `/mcp/plugin/<plugin_id>/enable`, Methods: []string{`POST`}, Domain: `mcp`, LegacySymbol: `mcp_enable_plugin`, GoPattern: `/mcp/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-148`, Endpoint: `/mcp/plugins`, Methods: []string{`GET`}, Domain: `mcp`, LegacySymbol: `mcp_list_plugins`, GoPattern: `/mcp/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-149`, Endpoint: `/mcp/tools`, Methods: []string{`GET`}, Domain: `mcp`, LegacySymbol: `mcp_get_enabled_tools`, GoPattern: `/mcp/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-150`, Endpoint: `/memory`, Methods: []string{`POST`}, Domain: `memory`, LegacySymbol: `memory_add`, GoPattern: `/memory`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-151`, Endpoint: `/memory/<memory_id>`, Methods: []string{`DELETE`}, Domain: `memory`, LegacySymbol: `memory_delete`, GoPattern: `/memory/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-152`, Endpoint: `/memory/<memory_id>/pin`, Methods: []string{`PUT`}, Domain: `memory`, LegacySymbol: `memory_toggle_pin`, GoPattern: `/memory/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-153`, Endpoint: `/memory/consolidate`, Methods: []string{`POST`}, Domain: `memory`, LegacySymbol: `memory_consolidate`, GoPattern: `/memory/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-154`, Endpoint: `/memory/profile`, Methods: []string{`POST`}, Domain: `memory`, LegacySymbol: `memory_update_profile`, GoPattern: `/memory/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-155`, Endpoint: `/memory/search`, Methods: []string{`POST`}, Domain: `memory`, LegacySymbol: `memory_search`, GoPattern: `/memory/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-156`, Endpoint: `/memory/stats`, Methods: []string{`GET`}, Domain: `memory`, LegacySymbol: `memory_get_stats`, GoPattern: `/memory/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-157`, Endpoint: `/models`, Methods: []string{`GET`}, Domain: `models`, LegacySymbol: `models_compat`, GoPattern: `/models`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-158`, Endpoint: `/multimodal/analyze`, Methods: []string{`POST`}, Domain: `multimodal`, LegacySymbol: `multimodal_analyze`, GoPattern: `/multimodal/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-159`, Endpoint: `/multimodal/chat`, Methods: []string{`POST`}, Domain: `multimodal`, LegacySymbol: `multimodal_chat`, GoPattern: `/multimodal/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-160`, Endpoint: `/multimodal/clear`, Methods: []string{`POST`}, Domain: `multimodal`, LegacySymbol: `multimodal_clear_history`, GoPattern: `/multimodal/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-161`, Endpoint: `/multimodal/history`, Methods: []string{`GET`}, Domain: `multimodal`, LegacySymbol: `multimodal_get_history`, GoPattern: `/multimodal/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-162`, Endpoint: `/multimodal/upload`, Methods: []string{`POST`}, Domain: `multimodal`, LegacySymbol: `multimodal_upload_image`, GoPattern: `/multimodal/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-163`, Endpoint: `/ops/campaigns`, Methods: []string{`POST`}, Domain: `ops`, LegacySymbol: `ops_campaigns_create`, GoPattern: `/ops/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-164`, Endpoint: `/ops/campaigns/<campaign_id>`, Methods: []string{`DELETE`}, Domain: `ops`, LegacySymbol: `ops_campaign_delete`, GoPattern: `/ops/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-165`, Endpoint: `/ops/campaigns/<campaign_id>/status`, Methods: []string{`POST`}, Domain: `ops`, LegacySymbol: `ops_campaign_status`, GoPattern: `/ops/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-166`, Endpoint: `/ops/overview`, Methods: []string{`GET`}, Domain: `ops`, LegacySymbol: `ops_overview`, GoPattern: `/ops/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-167`, Endpoint: `/performance/export`, Methods: []string{`GET`}, Domain: `performance`, LegacySymbol: `export_performance`, GoPattern: `/performance/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-168`, Endpoint: `/performance/stats`, Methods: []string{`GET`}, Domain: `performance`, LegacySymbol: `performance_stats`, GoPattern: `/performance/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-169`, Endpoint: `/playbooks`, Methods: []string{`POST`}, Domain: `playbooks`, LegacySymbol: `playbooks_create`, GoPattern: `/playbooks`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-170`, Endpoint: `/playbooks/<playbook_id>/run`, Methods: []string{`POST`}, Domain: `playbooks`, LegacySymbol: `playbooks_run`, GoPattern: `/playbooks/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-171`, Endpoint: `/privacy/delete`, Methods: []string{`POST`}, Domain: `privacy`, LegacySymbol: `privacy_delete_data`, GoPattern: `/privacy/delete`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-172`, Endpoint: `/privacy/export`, Methods: []string{`POST`}, Domain: `privacy`, LegacySymbol: `privacy_export_data`, GoPattern: `/privacy/export`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-173`, Endpoint: `/privacy/settings`, Methods: []string{`GET`, `POST`}, Domain: `privacy`, LegacySymbol: `privacy_settings_api`, GoPattern: `/privacy/settings`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-174`, Endpoint: `/project/activity`, Methods: []string{`GET`}, Domain: `project`, LegacySymbol: `project_activity`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-175`, Endpoint: `/project/batch`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_batch`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-176`, Endpoint: `/project/clear`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_clear_api`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-177`, Endpoint: `/project/config`, Methods: []string{`GET`, `POST`}, Domain: `project`, LegacySymbol: `project_config_api`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-178`, Endpoint: `/project/export`, Methods: []string{`GET`}, Domain: `project`, LegacySymbol: `project_export_api`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-179`, Endpoint: `/project/import`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_import_api`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-180`, Endpoint: `/project/milestones`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_milestones_create`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-181`, Endpoint: `/project/milestones/<milestone_id>`, Methods: []string{`DELETE`}, Domain: `project`, LegacySymbol: `project_milestones_delete`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-182`, Endpoint: `/project/milestones/<milestone_id>/status`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_milestones_status`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-183`, Endpoint: `/project/overview`, Methods: []string{`GET`}, Domain: `project`, LegacySymbol: `project_overview`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-184`, Endpoint: `/project/risks`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_risks_create`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-185`, Endpoint: `/project/risks/<risk_id>`, Methods: []string{`DELETE`}, Domain: `project`, LegacySymbol: `project_risks_delete`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-186`, Endpoint: `/project/risks/<risk_id>/status`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_risks_status`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-187`, Endpoint: `/project/stats`, Methods: []string{`GET`}, Domain: `project`, LegacySymbol: `project_stats_api`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-188`, Endpoint: `/project/tasks`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_tasks_create`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-189`, Endpoint: `/project/tasks/<task_id>`, Methods: []string{`DELETE`}, Domain: `project`, LegacySymbol: `project_tasks_delete`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-190`, Endpoint: `/project/tasks/<task_id>/status`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_tasks_update_status`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-191`, Endpoint: `/project/tasks/batch_status`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_tasks_batch_status`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-192`, Endpoint: `/project/tasks/reorder`, Methods: []string{`POST`}, Domain: `project`, LegacySymbol: `project_tasks_reorder`, GoPattern: `/project/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-193`, Endpoint: `/rag/add_text`, Methods: []string{`POST`}, Domain: `rag`, LegacySymbol: `rag_add_text`, GoPattern: `/rag/add_text`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-194`, Endpoint: `/rag/analysis`, Methods: []string{`GET`}, Domain: `rag`, LegacySymbol: `rag_analysis_route`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-195`, Endpoint: `/rag/batch_upload`, Methods: []string{`POST`}, Domain: `rag`, LegacySymbol: `rag_batch_upload`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-196`, Endpoint: `/rag/build-graph`, Methods: []string{`POST`}, Domain: `rag`, LegacySymbol: `build_rag_graph`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-197`, Endpoint: `/rag/chunk/<chunk_id>`, Methods: []string{`GET`}, Domain: `rag`, LegacySymbol: `rag_get_chunk`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-198`, Endpoint: `/rag/clear_cache`, Methods: []string{`POST`}, Domain: `rag`, LegacySymbol: `rag_clear_cache`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-199`, Endpoint: `/rag/delete/<doc_id>`, Methods: []string{`DELETE`}, Domain: `rag`, LegacySymbol: `rag_delete`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-200`, Endpoint: `/rag/documents`, Methods: []string{`GET`}, Domain: `rag`, LegacySymbol: `rag_documents_list`, GoPattern: `/rag/documents`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-201`, Endpoint: `/rag/preview/<doc_id>`, Methods: []string{`GET`}, Domain: `rag`, LegacySymbol: `rag_preview`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-202`, Endpoint: `/rag/search`, Methods: []string{`POST`}, Domain: `rag`, LegacySymbol: `rag_search`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-203`, Endpoint: `/rag/stats`, Methods: []string{`GET`}, Domain: `rag`, LegacySymbol: `rag_stats`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-204`, Endpoint: `/rag/upload`, Methods: []string{`POST`}, Domain: `rag`, LegacySymbol: `rag_upload`, GoPattern: `/rag/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `high`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-205`, Endpoint: `/release/overview`, Methods: []string{`GET`}, Domain: `release`, LegacySymbol: `release_overview`, GoPattern: `/release/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-206`, Endpoint: `/release/plans`, Methods: []string{`POST`}, Domain: `release`, LegacySymbol: `release_plans_create`, GoPattern: `/release/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-207`, Endpoint: `/release/plans/<plan_id>`, Methods: []string{`DELETE`}, Domain: `release`, LegacySymbol: `release_plan_delete`, GoPattern: `/release/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-208`, Endpoint: `/release/plans/<plan_id>/check`, Methods: []string{`POST`}, Domain: `release`, LegacySymbol: `release_plan_check`, GoPattern: `/release/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-209`, Endpoint: `/release/plans/<plan_id>/status`, Methods: []string{`POST`}, Domain: `release`, LegacySymbol: `release_plan_status`, GoPattern: `/release/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-210`, Endpoint: `/scenes/generate`, Methods: []string{`POST`}, Domain: `scenes`, LegacySymbol: `scenes_generate`, GoPattern: `/scenes/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-211`, Endpoint: `/scenes/history`, Methods: []string{`DELETE`}, Domain: `scenes`, LegacySymbol: `scenes_history_delete`, GoPattern: `/scenes/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-212`, Endpoint: `/scenes/list`, Methods: []string{`GET`}, Domain: `scenes`, LegacySymbol: `scenes_list`, GoPattern: `/scenes/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-213`, Endpoint: `/scheduler/tasks`, Methods: []string{`POST`}, Domain: `scheduler`, LegacySymbol: `create_scheduled_task`, GoPattern: `/scheduler/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-214`, Endpoint: `/search/global`, Methods: []string{`GET`}, Domain: `search`, LegacySymbol: `global_search`, GoPattern: `/search/global`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-215`, Endpoint: `/security/2fa/setup`, Methods: []string{`GET`, `POST`}, Domain: `security`, LegacySymbol: `setup_2fa`, GoPattern: `/security/2fa/setup`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-216`, Endpoint: `/security/audit`, Methods: []string{`GET`}, Domain: `security`, LegacySymbol: `security_audit_list`, GoPattern: `/security/audit`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-217`, Endpoint: `/security/audit/clear`, Methods: []string{`POST`}, Domain: `security`, LegacySymbol: `security_audit_clear`, GoPattern: `/security/audit/clear`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-218`, Endpoint: `/security/ip-whitelist`, Methods: []string{`DELETE`, `GET`, `POST`}, Domain: `security`, LegacySymbol: `ip_whitelist_api`, GoPattern: `/security/ip-whitelist`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-219`, Endpoint: `/security/ip-whitelist/mode`, Methods: []string{`POST`}, Domain: `security`, LegacySymbol: `ip_whitelist_mode_api`, GoPattern: `/security/ip-whitelist/mode`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-220`, Endpoint: `/security/status`, Methods: []string{`GET`}, Domain: `security`, LegacySymbol: `security_status`, GoPattern: `/security/status`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-221`, Endpoint: `/services/<service_id>/restart`, Methods: []string{`POST`}, Domain: `services`, LegacySymbol: `restart_service`, GoPattern: `/services/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-222`, Endpoint: `/services/health-check`, Methods: []string{`GET`}, Domain: `services`, LegacySymbol: `services_health_check`, GoPattern: `/services/health-check`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-223`, Endpoint: `/sidebar-icon`, Methods: []string{`GET`}, Domain: `sidebar_icon`, LegacySymbol: `sidebar_icon`, GoPattern: `/sidebar-icon`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-224`, Endpoint: `/stream`, Methods: []string{`POST`}, Domain: `stream`, LegacySymbol: `stream_endpoint`, GoPattern: `/stream`, CoveredByGo: true, HandlerMode: `go_provider_or_python_worker`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-225`, Endpoint: `/system/metrics`, Methods: []string{`GET`}, Domain: `system`, LegacySymbol: `system_metrics`, GoPattern: `/system/metrics`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-226`, Endpoint: `/templates/analysis`, Methods: []string{`GET`}, Domain: `templates`, LegacySymbol: `templates_analysis`, GoPattern: `/templates/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-227`, Endpoint: `/templates/search`, Methods: []string{`GET`}, Domain: `templates`, LegacySymbol: `search_templates`, GoPattern: `/templates/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-228`, Endpoint: `/tool/execute`, Methods: []string{`POST`}, Domain: `tool`, LegacySymbol: `tool_execute`, GoPattern: `/tool/execute`, CoveredByGo: true, HandlerMode: `permission_guarded`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-229`, Endpoint: `/tts`, Methods: []string{`POST`}, Domain: `tts`, LegacySymbol: `tts_endpoint`, GoPattern: `/tts`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-230`, Endpoint: `/wallpaper`, Methods: []string{`GET`}, Domain: `wallpaper`, LegacySymbol: `wallpaper`, GoPattern: `/wallpaper`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-231`, Endpoint: `/web/fetch`, Methods: []string{`POST`}, Domain: `web`, LegacySymbol: `web_fetch_api`, GoPattern: `/web/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-232`, Endpoint: `/web/search`, Methods: []string{`POST`}, Domain: `web`, LegacySymbol: `web_search_api`, GoPattern: `/web/`, CoveredByGo: true, HandlerMode: `structured_unavailable_until_ported`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-233`, Endpoint: `/welcome-img`, Methods: []string{`GET`}, Domain: `welcome_img`, LegacySymbol: `welcome_img`, GoPattern: `/welcome-img`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-234`, Endpoint: `/workflow`, Methods: []string{`POST`}, Domain: `workflow`, LegacySymbol: `workflow_create`, GoPattern: `/workflow`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-235`, Endpoint: `/workflow/<workflow_id>`, Methods: []string{`DELETE`}, Domain: `workflow`, LegacySymbol: `workflow_delete`, GoPattern: `/workflow/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-236`, Endpoint: `/workflow/<workflow_id>/execute`, Methods: []string{`POST`}, Domain: `workflow`, LegacySymbol: `workflow_execute`, GoPattern: `/workflow/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-237`, Endpoint: `/workflow/execute`, Methods: []string{`POST`}, Domain: `workflow`, LegacySymbol: `workflow_execute_inline`, GoPattern: `/workflow/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `critical`, RequiresAuth: true, RequiresCSRF: true, RequiresPermission: true},
	{ID: `LEGACY-ROUTE-238`, Endpoint: `/workflow/node-types`, Methods: []string{`GET`}, Domain: `workflow`, LegacySymbol: `workflow_get_node_types`, GoPattern: `/workflow/`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-239`, Endpoint: `/workflows`, Methods: []string{`GET`}, Domain: `workflows`, LegacySymbol: `workflow_list`, GoPattern: `/workflows`, CoveredByGo: true, HandlerMode: `go_durable`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-240`, Endpoint: `/workspace/projects`, Methods: []string{`POST`}, Domain: `workspace`, LegacySymbol: `create_workspace_project`, GoPattern: `/workspace/projects`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `medium`, RequiresAuth: false, RequiresCSRF: true, RequiresPermission: false},
	{ID: `LEGACY-ROUTE-241`, Endpoint: `/workspace/projects/overview`, Methods: []string{`GET`}, Domain: `workspace`, LegacySymbol: `workspace_projects_overview`, GoPattern: `/workspace/projects/`, CoveredByGo: true, HandlerMode: `go_handler`, RiskLevel: `low`, RequiresAuth: false, RequiresCSRF: false, RequiresPermission: false},
}

var legacyRouteContracts = buildRouteContracts(legacyRouteContractSeeds)

func legacyRouteContractStats() map[string]int {
	stats := map[string]int{"total": len(legacyRouteContracts), "covered": 0, "missing": 0, "high_risk": 0}
	for _, contract := range legacyRouteContracts {
		if contract.CoveredByGo {
			stats["covered"]++
		} else {
			stats["missing"]++
		}
		if contract.RiskLevel == "high" || contract.RiskLevel == "critical" {
			stats["high_risk"]++
		}
	}
	return stats
}

func legacyRouteContractsByDomain(domain string) []routeContract {
	out := []routeContract{}
	for _, contract := range legacyRouteContracts {
		if contract.Domain == domain {
			out = append(out, contract)
		}
	}
	return out
}
