#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the Go-side legacy route parity contract.

This script is kept for auditors that still have a private copy of the removed
legacy monolith. The checked-in generated Go catalog is the source of truth in
the public tree after physical deletion of that monolith.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass


APP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ROOT_DIR = os.path.abspath(os.path.join(APP_DIR, "..", ".."))
LEGACY_MONOLITH_FILE = os.path.join(
    APP_DIR,
    os.environ.get("KAGUYA_LEGACY_MONOLITH", "legacy_monolith.py"),
)
GO_SERVER = os.path.join(ROOT_DIR, "resources", "go-backend", "server.go")
OUT_FILE = os.path.join(ROOT_DIR, "resources", "go-backend", "route_contract_generated.go")


@dataclass(frozen=True)
class Route:
    endpoint: str
    methods: tuple[str, ...]
    symbol: str


def read(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="ignore") as handle:
        return handle.read()


def extract_routes() -> list[Route]:
    text = read(LEGACY_MONOLITH_FILE)
    pattern = re.compile(
        r"@app\.route\(\s*['\"]([^'\"]+)['\"](?P<args>[^)]*)\)\s*\n(?:@[^\n]+\n)*def\s+([A-Za-z_][A-Za-z0-9_]*)",
        re.MULTILINE,
    )
    routes: dict[str, Route] = {}
    for match in pattern.finditer(text):
        endpoint = match.group(1)
        args = match.group("args") or ""
        symbol = match.group(3)
        methods = re.findall(r"['\"](GET|POST|PUT|PATCH|DELETE|OPTIONS)['\"]", args)
        if not methods:
            methods = ["GET"]
        routes[endpoint] = Route(endpoint, tuple(sorted(set(methods))), symbol)
    return [routes[key] for key in sorted(routes)]


def extract_go_routes() -> set[str]:
    if not os.path.exists(GO_SERVER):
        return set()
    text = read(GO_SERVER)
    return set(re.findall(r"mux\.HandleFunc\(\s*['\"]([^'\"]+)['\"]", text))


def covered_by_go(endpoint: str, go_routes: set[str]) -> tuple[bool, str]:
    if endpoint in go_routes:
        return True, endpoint
    for route in sorted(go_routes, key=len, reverse=True):
        if route != "/" and route.endswith("/") and endpoint.startswith(route):
            return True, route
    return False, ""


def domain_for(endpoint: str) -> str:
    first = endpoint.strip("/").split("/", 1)[0]
    if first == "":
        return "home"
    return first.replace("-", "_")


def risk_for(endpoint: str, methods: tuple[str, ...]) -> str:
    e = endpoint.lower()
    mutating = any(method in {"POST", "PUT", "PATCH", "DELETE"} for method in methods)
    critical_tokens = ("terminal", "execute", "run-project", "compile", "deploy", "delete", "privacy/delete")
    high_tokens = ("write", "upload", "import", "open-project", "token", "admin", "auth", "permission")
    if any(token in e for token in critical_tokens):
        return "critical"
    if any(token in e for token in high_tokens):
        return "high"
    if mutating:
        return "medium"
    return "low"


def mode_for(endpoint: str) -> str:
    e = endpoint.lower()
    durable = (
        "/api/device/",
        "/api/account/",
        "/account/",
        "/auth/",
        "/privacy/",
        "/kb/",
        "/project/",
        "/workflow",
        "/workflows",
        "/playbooks",
        "/integrations",
        "/agent/audit/",
    )
    delegated = (
        "/rag/",
        "/web/",
        "/tts",
        "/mcp/",
        "/multimodal/",
        "/finetune/",
        "/deploy/",
        "/agent/browser/",
        "/agent/file-analyzer/",
    )
    if any(e.startswith(prefix) for prefix in durable):
        return "go_durable"
    if any(e.startswith(prefix) for prefix in delegated):
        return "structured_unavailable_until_ported"
    if "chat" in e or "deepseek" in e or "stream" in e:
        return "go_provider_or_python_worker"
    if e.startswith("/agent/terminal") or e.startswith("/tool/") or e.startswith("/code/"):
        return "permission_guarded"
    return "go_handler"


def bool_lit(value: bool) -> str:
    return "true" if value else "false"


def go_string(value: str) -> str:
    return "`" + value.replace("`", "` + \"`\" + `") + "`"


def render() -> str:
    routes = extract_routes()
    go_routes = extract_go_routes()
    lines: list[str] = []
    lines.append("// Code generated by resources/python-app/scripts/generate_go_route_contract.py; DO NOT EDIT.")
    lines.append("// This catalog is a legacy monolith deletion gate, not proof of behavior parity.")
    lines.append("package main")
    lines.append("")
    lines.append("type routeContract struct {")
    lines.append("\tID string")
    lines.append("\tEndpoint string")
    lines.append("\tMethods []string")
    lines.append("\tDomain string")
    lines.append("\tLegacySymbol string")
    lines.append("\tGoPattern string")
    lines.append("\tCoveredByGo bool")
    lines.append("\tHandlerMode string")
    lines.append("\tRiskLevel string")
    lines.append("\tRequiresAuth bool")
    lines.append("\tRequiresCSRF bool")
    lines.append("\tRequiresPermission bool")
    lines.append("\tRequestContract []string")
    lines.append("\tResponseContract []string")
    lines.append("\tFailureContract []string")
    lines.append("\tMigrationNotes []string")
    lines.append("}")
    lines.append("")
    lines.append("var legacyRouteContracts = []routeContract{")
    for index, route in enumerate(routes, start=1):
        covered, pattern = covered_by_go(route.endpoint, go_routes)
        risk = risk_for(route.endpoint, route.methods)
        mode = mode_for(route.endpoint)
        domain = domain_for(route.endpoint)
        methods = ", ".join(go_string(method) for method in route.methods)
        requires_auth = route.endpoint.startswith("/auth/") or route.endpoint.startswith("/account/") or risk in {"high", "critical"}
        requires_csrf = any(method in {"POST", "PUT", "PATCH", "DELETE"} for method in route.methods)
        requires_permission = risk in {"high", "critical"} or route.endpoint.startswith("/agent/")
        lines.append("\t{")
        lines.append(f"\t\tID: {go_string(f'LEGACY-ROUTE-{index:03d}')},")
        lines.append(f"\t\tEndpoint: {go_string(route.endpoint)},")
        lines.append(f"\t\tMethods: []string{{{methods}}},")
        lines.append(f"\t\tDomain: {go_string(domain)},")
        lines.append(f"\t\tLegacySymbol: {go_string(route.symbol)},")
        lines.append(f"\t\tGoPattern: {go_string(pattern)},")
        lines.append(f"\t\tCoveredByGo: {bool_lit(covered)},")
        lines.append(f"\t\tHandlerMode: {go_string(mode)},")
        lines.append(f"\t\tRiskLevel: {go_string(risk)},")
        lines.append(f"\t\tRequiresAuth: {bool_lit(requires_auth)},")
        lines.append(f"\t\tRequiresCSRF: {bool_lit(requires_csrf)},")
        lines.append(f"\t\tRequiresPermission: {bool_lit(requires_permission)},")
        lines.append("\t\tRequestContract: []string{")
        lines.append(f"\t\t\t{go_string('accept the legacy request shape used by ' + route.symbol)},")
        lines.append("\t\t\t`normalize camelCase and snake_case fields before business logic`,")
        lines.append("\t\t\t`reject malformed JSON with a structured JSON error`,")
        lines.append("\t\t\t`do not read files or execute commands before authorization`,")
        lines.append("\t\t},")
        lines.append("\t\tResponseContract: []string{")
        lines.append("\t\t\t`return application/json for JSON APIs and text/event-stream for SSE routes`,")
        lines.append("\t\t\t`do not return HTML traceback pages for API failures`,")
        lines.append("\t\t\t`never include plaintext API keys, tokens, or local secrets`,")
        lines.append("\t\t\t`include success/available/error fields when a capability is unavailable`,")
        lines.append("\t\t},")
        lines.append("\t\tFailureContract: []string{")
        lines.append("\t\t\t`return structured unavailable when an optional Python worker or model dependency is missing`,")
        lines.append("\t\t\t`return permission_required before any high-risk side effect`,")
        lines.append("\t\t\t`write an audit record for allowed and denied high-risk actions`,")
        lines.append("\t\t\t`keep desktop fallback honest: mode=go must not imply full Python behavior parity`,")
        lines.append("\t\t},")
        lines.append("\t\tMigrationNotes: []string{")
        lines.append(f"\t\t\t{go_string('legacy endpoint ' + route.endpoint + ' is tracked for physical monolith deletion')},")
        lines.append(f"\t\t\t{go_string('legacy Flask function: ' + route.symbol)},")
        lines.append(f"\t\t\t{go_string('current Go handler pattern: ' + (pattern or 'missing'))},")
        lines.append(f"\t\t\t{go_string('domain owner: ' + domain)},")
        lines.append(f"\t\t\t{go_string('risk classification: ' + risk)},")
        lines.append(f"\t\t\t{go_string('handler mode: ' + mode)},")
        lines.append("\t\t\t`route coverage is mandatory but behavior tests are the deletion gate`,")
        lines.append("\t\t\t`if this route mutates state, tests must cover restart persistence or explicit non-persistence`,")
        lines.append("\t\t\t`if this route touches workspace paths, tests must cover traversal and symlink escape`,")
        lines.append("\t\t\t`if this route calls providers, tests must use fake upstreams and assert no key leakage`,")
        lines.append("\t\t},")
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    lines.append("func legacyRouteContractStats() map[string]int {")
    lines.append("\tstats := map[string]int{\"total\": len(legacyRouteContracts), \"covered\": 0, \"missing\": 0, \"high_risk\": 0}")
    lines.append("\tfor _, contract := range legacyRouteContracts {")
    lines.append("\t\tif contract.CoveredByGo {")
    lines.append("\t\t\tstats[\"covered\"]++")
    lines.append("\t\t} else {")
    lines.append("\t\t\tstats[\"missing\"]++")
    lines.append("\t\t}")
    lines.append("\t\tif contract.RiskLevel == \"high\" || contract.RiskLevel == \"critical\" {")
    lines.append("\t\t\tstats[\"high_risk\"]++")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn stats")
    lines.append("}")
    lines.append("")
    lines.append("func legacyRouteContractsByDomain(domain string) []routeContract {")
    lines.append("\tout := []routeContract{}")
    lines.append("\tfor _, contract := range legacyRouteContracts {")
    lines.append("\t\tif contract.Domain == domain {")
    lines.append("\t\t\tout = append(out, contract)")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn out")
    lines.append("}")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not os.path.exists(LEGACY_MONOLITH_FILE):
        raise SystemExit(f"missing {LEGACY_MONOLITH_FILE}")
    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render())
    print(OUT_FILE)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

