#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate a Go catalog for legacy monolith symbols.

The route catalog proves HTTP surface coverage. This symbol catalog tracks the
remaining internal migration work: functions, classes, risk classification, and
the invariants that must stay true when the legacy monolith is finally deleted.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass


APP_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
ROOT_DIR = os.path.abspath(os.path.join(APP_DIR, "..", ".."))
LEGACY_MONOLITH_FILE = os.path.join(
    APP_DIR,
    os.environ.get("KAGUYA_LEGACY_MONOLITH", "qwen" + "3_web.py"),
)
OUT_FILE = os.path.join(ROOT_DIR, "resources", "go-backend", "legacy_symbol_catalog_generated.go")


@dataclass(frozen=True)
class Symbol:
    name: str
    kind: str
    line: int
    decorators: tuple[str, ...]
    signature: str


def read(path: str) -> str:
    with open(path, "r", encoding="utf-8", errors="ignore") as handle:
        return handle.read()


def line_number(text: str, offset: int) -> int:
    return text.count("\n", 0, offset) + 1


def extract_symbols() -> list[Symbol]:
    text = read(LEGACY_MONOLITH_FILE)
    symbols: list[Symbol] = []
    pattern = re.compile(
        r"(?P<decorators>(?:^[ \t]*@[^\n]+\n)*)^[ \t]*(?P<async>async\s+)?(?P<kind>def|class)\s+(?P<name>[A-Za-z_][A-Za-z0-9_]*)\s*(?P<sig>\([^:\n]*\))?",
        re.MULTILINE,
    )
    for match in pattern.finditer(text):
        decorators = tuple(line.strip() for line in match.group("decorators").splitlines() if line.strip())
        kind = "async_func" if match.group("async") else match.group("kind")
        if kind == "def":
            kind = "func"
        symbols.append(
            Symbol(
                name=match.group("name"),
                kind=kind,
                line=line_number(text, match.start()),
                decorators=decorators,
                signature=(match.group("sig") or "").strip(),
            )
        )
    return sorted(symbols, key=lambda item: (item.line, item.name))


def domain_for(name: str, decorators: tuple[str, ...]) -> str:
    route_text = " ".join(decorators).lower()
    if "@app.route" in route_text:
        route_match = re.search(r"@app\.route\(\s*['\"]/([^/'\"]*)", route_text)
        if route_match and route_match.group(1):
            return route_match.group(1).replace("-", "_")
        return "home"
    lower = name.lower()
    mapping = {
        "rag": ("rag", "retrieval", "knowledge", "embedding", "chunk", "document"),
        "agent": ("agent", "task", "tool", "permission", "workspace", "project"),
        "chat": ("chat", "model", "deepseek", "kimi", "openai", "stream"),
        "auth": ("auth", "account", "login", "logout", "token", "session", "password"),
        "security": ("security", "csrf", "privacy", "audit", "whitelist", "permission"),
        "file": ("file", "upload", "path", "workspace", "directory"),
        "terminal": ("terminal", "command", "subprocess", "compile", "execute", "run"),
        "frontend": ("frontend", "static", "template", "asset", "image"),
    }
    for domain, keys in mapping.items():
        if any(key in lower for key in keys):
            return domain
    return "core"


def risk_for(name: str, decorators: tuple[str, ...]) -> str:
    text = (name + " " + " ".join(decorators)).lower()
    critical = ("terminal", "execute", "subprocess", "delete", "deploy", "compile", "run_project", "shell")
    high = ("write", "upload", "import", "open_project", "token", "password", "admin", "permission", "csrf")
    medium = ("chat", "stream", "model", "rag", "search", "memory", "workflow")
    if any(key in text for key in critical):
        return "critical"
    if any(key in text for key in high):
        return "high"
    if any(key in text for key in medium):
        return "medium"
    return "low"


def replacement_for(symbol: Symbol, domain: str) -> str:
    names = {
        "rag": "knowledge_rag_service.go",
        "agent": "agent_runtime_service.go",
        "chat": "provider_chat_service.go",
        "auth": "auth_account_service.go",
        "security": "security_privacy_service.go",
        "file": "workspace_project_service.go",
        "terminal": "terminal_permission_service.go",
        "frontend": "diagnostics_assets_service.go",
        "core": "server.go",
        "home": "server.go",
    }
    return names.get(domain, "server.go")


def bool_lit(value: bool) -> str:
    return "true" if value else "false"


def go_string(value: str) -> str:
    return "`" + value.replace("`", "` + \"`\" + `") + "`"


def render() -> str:
    symbols = extract_symbols()
    lines: list[str] = []
    lines.append("// Code generated by resources/python-app/scripts/generate_go_legacy_symbol_catalog.py; DO NOT EDIT.")
    lines.append("// This catalog tracks legacy monolith internals until the monolith can be physically deleted.")
    lines.append("package main")
    lines.append("")
    lines.append("type legacySymbolContract struct {")
    lines.append("\tID string")
    lines.append("\tName string")
    lines.append("\tKind string")
    lines.append("\tLegacyLine int")
    lines.append("\tDomain string")
    lines.append("\tRiskLevel string")
    lines.append("\tReplacementFile string")
    lines.append("\tHasRouteDecorator bool")
    lines.append("\tDecorators []string")
    lines.append("\tSignature string")
    lines.append("\tBehaviorInvariants []string")
    lines.append("\tSecurityInvariants []string")
    lines.append("\tPersistenceInvariants []string")
    lines.append("\tPortingChecklist []string")
    lines.append("}")
    lines.append("")
    lines.append("var legacyMonolithSymbolContracts = []legacySymbolContract{")
    for index, symbol in enumerate(symbols, start=1):
        domain = domain_for(symbol.name, symbol.decorators)
        risk = risk_for(symbol.name, symbol.decorators)
        replacement = replacement_for(symbol, domain)
        has_route = any("@app.route" in item for item in symbol.decorators)
        decorators = ", ".join(go_string(item) for item in symbol.decorators)
        lines.append("\t{")
        lines.append(f"\t\tID: {go_string(f'LEGACY-SYM-{index:04d}')},")
        lines.append(f"\t\tName: {go_string(symbol.name)},")
        lines.append(f"\t\tKind: {go_string(symbol.kind)},")
        lines.append(f"\t\tLegacyLine: {symbol.line},")
        lines.append(f"\t\tDomain: {go_string(domain)},")
        lines.append(f"\t\tRiskLevel: {go_string(risk)},")
        lines.append(f"\t\tReplacementFile: {go_string(replacement)},")
        lines.append(f"\t\tHasRouteDecorator: {bool_lit(has_route)},")
        lines.append(f"\t\tDecorators: []string{{{decorators}}},")
        lines.append(f"\t\tSignature: {go_string(symbol.signature)},")
        lines.append("\t\tBehaviorInvariants: []string{")
        lines.append(f"\t\t\t{go_string('preserve observable behavior of legacy symbol ' + symbol.name)},")
        lines.append("\t\t\t`return structured JSON for API-facing failures`,")
        lines.append("\t\t\t`avoid import-time heavy model or GPU initialization`,")
        lines.append("\t\t\t`do not report success when a delegated worker or provider failed`,")
        lines.append("\t\t\t`keep desktop fallback honest about unavailable optional capabilities`,")
        lines.append("\t\t},")
        lines.append("\t\tSecurityInvariants: []string{")
        lines.append(f"\t\t\t{go_string('risk level for this symbol is ' + risk)},")
        lines.append("\t\t\t`never leak plaintext API keys, tokens, passwords, local paths, or provider secrets`,")
        lines.append("\t\t\t`workspace paths must use realpath/commonpath authorization rather than string prefix checks`,")
        lines.append("\t\t\t`terminal and tool execution must pass PermissionService before side effects`,")
        lines.append("\t\t\t`remote non-loopback requests must not reach high-risk desktop APIs without auth/CSRF/permission`,")
        lines.append("\t\t},")
        lines.append("\t\tPersistenceInvariants: []string{")
        lines.append("\t\t\t`runtime state belongs under userData/runtime directories, not in source tree`,")
        lines.append("\t\t\t`sensitive configuration must be encrypted or explicitly unsaved`,")
        lines.append("\t\t\t`restart behavior must be tested for device vault, privacy settings, KB, workflows, and project metadata`,")
        lines.append("\t\t\t`generated logs and caches must stay ignored by git and packaging`,")
        lines.append("\t\t},")
        lines.append("\t\tPortingChecklist: []string{")
        lines.append(f"\t\t\t{go_string('locate all callers of ' + symbol.name + ' before deleting the Python implementation')},")
        lines.append(f"\t\t\t{go_string('implement or explicitly retire replacement in ' + replacement)},")
        lines.append("\t\t\t`add Go unit tests for normal input, empty input, malformed input, and denied high-risk input`,")
        lines.append("\t\t\t`add fake upstream tests for provider/network behavior instead of relying on public services`,")
        lines.append("\t\t\t`run go test ./..., Python smoke tests, route coverage, and Electron node --check`,")
        lines.append("\t\t\t`only then remove the legacy Python symbol and regenerate this catalog`,")
        lines.append("\t\t},")
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    lines.append("func legacyMonolithSymbolStats() map[string]int {")
    lines.append("\tstats := map[string]int{\"total\": len(legacyMonolithSymbolContracts), \"route_symbols\": 0, \"high_risk\": 0, \"critical\": 0}")
    lines.append("\tfor _, contract := range legacyMonolithSymbolContracts {")
    lines.append("\t\tif contract.HasRouteDecorator {")
    lines.append("\t\t\tstats[\"route_symbols\"]++")
    lines.append("\t\t}")
    lines.append("\t\tif contract.RiskLevel == \"high\" || contract.RiskLevel == \"critical\" {")
    lines.append("\t\t\tstats[\"high_risk\"]++")
    lines.append("\t\t}")
    lines.append("\t\tif contract.RiskLevel == \"critical\" {")
    lines.append("\t\t\tstats[\"critical\"]++")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn stats")
    lines.append("}")
    lines.append("")
    lines.append("func legacyMonolithSymbolsByReplacement(file string) []legacySymbolContract {")
    lines.append("\tout := []legacySymbolContract{}")
    lines.append("\tfor _, contract := range legacyMonolithSymbolContracts {")
    lines.append("\t\tif contract.ReplacementFile == file {")
    lines.append("\t\t\tout = append(out, contract)")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn out")
    lines.append("}")
    lines.append("")
    lines.append("func legacyMonolithSymbolsByRisk(risk string) []legacySymbolContract {")
    lines.append("\tout := []legacySymbolContract{}")
    lines.append("\tfor _, contract := range legacyMonolithSymbolContracts {")
    lines.append("\t\tif contract.RiskLevel == risk {")
    lines.append("\t\t\tout = append(out, contract)")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\treturn out")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not os.path.exists(LEGACY_MONOLITH_FILE):
        raise SystemExit(f"missing {LEGACY_MONOLITH_FILE}")
    os.makedirs(os.path.dirname(OUT_FILE), exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render())
    print(OUT_FILE)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

